spring:
  application:
    name: distributed-kv-store

server:
  port: 8081

cluster:
  selfId: 1
  nodes:
    - id: 1
      host: localhost
      port: 8081
      isLeader: true
    - id: 2
      host: localhost
      port: 8082
      isLeader: false
    - id: 3
      host: localhost
      port: 8083
      isLeader: false
